[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_PUSHER_APP_ID = ""
  NEXT_PUBLIC_PUSHER_KEY = ""
  NEXT_PUBLIC_PUSHER_CLUSTER = ""
  NEXT_PUBLIC_TWILIO_PHONE_NUMBER = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
